Updated to ox
Qbox-project/qbx_cityhall pull request #2
Opened 2022-10-02 07:58 UTC by Scullyy

**Describe Pull request**
Updated to ox

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-10-02 08:11 UTC, trclassic92 requested changes

2022-10-02 08:11 UTC, trclassic92 commented on README.md
> +- [qb-phone](https://github.com/qbcore-framework/qb-phone) (Required)
[qb-phone](https://github.com/QBCore-Remastered/qb-phone)

2022-10-02 09:10 UTC, Scullyy commented on README.md
> +- [qb-phone](https://github.com/qbcore-framework/qb-phone) (Required)
Fixed

2022-10-02 17:33 UTC, trclassic92 approved these changes

2022-10-02 18:20 UTC, ihyajb approved these changes

2022-10-02 22:22 UTC, trclassic92 approved these changes

2022-10-04 22:30 UTC, izMystic approved these changes

2022-10-05 03:35 UTC, izMystic approved these changes

2022-10-05 03:37 UTC, izMystic commented
@ChatDisabled merge

2022-10-05 22:23 UTC, merged