refactor(locales): qb to ox
Qbox-project/qbx_cityhall pull request #35
Opened 2024-01-21 01:40 UTC by MafewTM

## Description

Switches over to the ox locales instead of the old qb locales

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-02-07 18:56 UTC, solareon requested changes

2024-02-07 18:56 UTC, solareon commented on client/main.lua
> +
```suggestion
```
Use fxmanifest locale

2024-02-07 18:56 UTC, solareon commented on server/main.lua
> +
```suggestion
```
Use fxmanifest locale

2024-02-07 18:56 UTC, solareon commented on fxmanifest.lua
```suggestion

ox_lib 'locale'

```
Magic

2024-02-07 18:57 UTC, solareon approved these changes

2024-02-11 23:01 UTC, BerkieBb approved these changes

2024-02-11 23:01 UTC, BerkieBb commented
Fix lint issues

2024-02-11 23:07 UTC, merged